title: GitHub ds. Pierson College
description: > # this means to ignore newlines until "baseurl:"a
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ds. Pierson College # add your name
author-img: Pierson_logo_200.png # add your photo
about-author: GitHub Pages. # add description
social-twitter: Moorlag
social-github: piersoncollege # add your Github handle
social-linkedin: Moorlag

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
